### ISSUE TITLE
Line number support

### ISSUE THREAD

**Issue by funtion** [egoist/hanabi#2]
Is there any plan to support line number?

**Comment by egoist** [comment]
You can achieve this easily by yourself:

```js
let lineNumber = 0
let out = hanabi(code)
  .replace(/^/gm, m => {
    return `<span style="width: 30px; display: inline-block">${++lineNumber}</span>`
  })
```

And how it looks like:

<img width="424" alt="2017-02-23 8 52 11" src="https://cloud.githubusercontent.com/assets/8784712/23259839/ff7d187e-fa09-11e6-9943-6f55b2b7716f.png">
