### ISSUE TITLE
HTML entities

### ISSUE THREAD

**Issue by xCss** [egoist/hanabi#5]
## input:
``` js
let lineNumber = 0
let out = hanabi(code)
  .replace(/^/gm, m => {
    return `<span style="width: 30px; display: inline-block">${++lineNumber}</span>`
  })
```

## output:
``` js
let lineNumber = 0
let out = hanabi(code)
  .replace(/^/gm, m =&gt; { // '>' => '&gt;'
    return `<span style="width: 30px; display: inline-block">${++lineNumber}</span>`
  })
```
Actually, I want to get `>` instead of `&gt;`.
In the code block, I think this replacement should not exist.

Or can you give an option to let the user choose whether to perform the replacement?

**Comment by Swizz** [comment]
FYI 

https://github.com/egoist/hanabi/blob/2cc513e20e830c46259f9c82364041775b317cde/src/index.js#L20-L22

Looks like a desired behavior to make clear of the separation of the HTML code to make the hilight even possible and the HTML code you want to keep as text (for being hilighted)

**Comment by xCss** [comment]
@Swizz ，Ok, i got it! It's my logical mistake.

Thx!
