### ISSUE TITLE
A little bug in code highlight

### ISSUE THREAD

**Issue by Singularity0909** [egoist/hanabi#6]
"&" changed into "&amp;"
I would much appreciate it if you could fix it
![image](https://user-images.githubusercontent.com/44798266/65608318-9eb76c00-dfe0-11e9-8389-d83b0caf57d5.png)

**Comment by Singularity0909** [comment]
&a m p;

**Comment by egoist** [comment]
This module doesn't transform `&` into `&amp;` 😅

**Comment by Singularity0909** [comment]
umm...  Maybe you can have a try. A friend of mine is faced with the same problem.

**Comment by Singularity0909** [comment]
Oh,  maybe I'm using another version Orz. hanabi-browser-bundle.  Sorry to bother you.

**Comment by Singularity0909** [comment]
I'm sorry to bother you as I have mistaken the other one's work [hanabi-browser](https://github.com/neko-dev/hanabi-browser) for yours.

**Comment by xuanxiaodeyu** [comment]
> I'm sorry to bother you as I have mistaken the other one's work [hanabi-browser](https://github.com/neko-dev/hanabi-browser) for yours.

@Singularity0909 so have you solved this problem?
